name: SEU Auto Temperature
on:
  schedule:
    - cron: '00 01 * * *'
    # cron表达式，时区是UTC时间，比我们早8小时，如上所表示的是每天UTC时间的1点整， 北京时间的9点0分（24点整）
    # 可在此网站查询UTC时间和北京时间的换算关系 https://datetime360.com/cn/utc-beijing-time/
  watch:
    types: started
  repository_dispatch:
  workflow_dispatch:

jobs:
  Temperature:
    runs-on: ubuntu-18.04
    if: github.event.repository.owner.id == github.event.sender.id
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
    - name: Run
      env:
        TZ: Asia/Shanghai
        ID: ${{ secrets.ID }}
        PASSWORD: ${{ secrets.PASSWORD }}
        NAME: ${{ secrets.NAME }}
        KU: ${{ secrets.KU }}
        SERVERCHAN: ${{ secrets.SERVERCHAN }}
      run: |
        bash Init_Building_Dependencies.sh
        python3 auto_temperature.py